### PR TITLE
Make start script actually symlink themes and config.

### PR DESCRIPTION
**Pull request by EpocSquadron**
This addresses #1 and #2

### CODE REVIEW

**Comment by pilwon** [comment]
@EpocSquadron Thanks for your PR.

**Comment by EpocSquadron** [comment]
You're welcome. 

How long until the docker registry gets the updated build?

**Comment by pilwon** [comment]
@EpocSquadron You can already use the new trusted build w/ your change. (`docker pull dockerfile/ghost`) One minor problem found in your modification is that it deletes the default `casper` theme. I'm trying to see what's the best fix for that.

**Comment by pilwon** [comment]
@EpocSquadron Made this change a33ebd04f47b1a074bd6c70d96376ab96902f96e and it seems to work well.

**Pull request merged**
