### PR TITLE
Fix Symlink data directory

### PR DESCRIPTION
**Pull request by harlley**

### CODE REVIEW

**Comment by pilwon** [comment]
@Harlley PR description please.

**Comment by thomasschmit** [comment]
@pilwon, this pull request allow to prevent the use of an override folder.

**Comment by pilwon** [comment]
@Harlley I'm closing this issue as this PR prevents the use of override directories as @le-cerf described... which I believe is actually not what we want. Closing the PR now but you can open a new PR with better description of your PR explaining why we need such change if you feel this is necessary to be merged.

**Comment by thomasschmit** [comment]
@pilwon, why do you want to use override directories?

**Comment by pilwon** [comment]
@le-cerf Please see the Usage section in README

**Comment by thomasschmit** [comment]
@pilwon, but why not to place those files and folders in the default directory rather than using an override directory and symbolic links?

**Comment by pilwon** [comment]
@le-cerf It wipes out some default subdirectories that you may want to keep in there.

**Comment by thomasschmit** [comment]
@pilwon, the Ghost guide itself writes in the default directory : http://docs.ghost.org/themes/.

**Comment by pilwon** [comment]
@le-cerf Yes, and that's why when you mount a volume at the default directory the mounted volume overrides the default subdirectories that Ghost writes to that default directory. This override technique is a necessary hack for more advanced setup and you will get what I explained here more easily when you actually meet a situation like that.

If you feel this sophistication is not what you desire for your project, please go ahead and fork this project to create your own Dockerfile. If you find anything is broken, then please open a new issue and submit PR for it.

**Pull request closed without merging**
