### PR TITLE
Allow execution with a dedicated ghost user so ghost execute as non root

### PR DESCRIPTION
**Pull request by revollat**

### CODE REVIEW

**Comment by josephpage** [comment]
What about using "USER" instruction ? 
https://docs.docker.com/reference/builder/#user

**Comment by revollat** [comment]
I tried USER instruction :) but it seems that the Volumes are mounted as root (the user who runs the Docker daemon) and "ghost" user can't run node without errors ... 
is it a feature ? can we hack this ? any informations welcome.
See also http://stackoverflow.com/questions/24308760/running-app-inside-docker-as-non-root-user

**Comment by pilwon** [comment]
@revollat Did you test with this updated Dockerfile? Isn't `ghost.ghost` supposed to be `ghost:ghost`?

```
chown [OPTION]... [OWNER][:[GROUP]] FILE...
```

Also, I those image manipulation commands are better be in Dockerfile rather than `start.bash`. This script is purely for starting up the app with some on-the-fly hacks.

**Comment by revollat** [comment]
I start working yesterday on it (forked at commit 9c202be964932466a77ce707605b5124e1a43e87) so I have the last Dockerfile the only update you made since is the README.md file
https://github.com/revollat/docker-ghost/commits/master

WIth chown command  usr.usr or usr:usr works the same way (don't ask me why :))

I agree with you, I would like to do this in the dockerfile but since the volume are mounted as root ther is error when trying to starts node with ghost user ... the (only?) way to get this work is to change permission on runtime ... 

See http://stackoverflow.com/questions/24308760/running-app-inside-docker-as-non-root-user

**Comment by pilwon** [comment]
@revollat Thanks for the PR-

**Comment by revollat** [comment]
it's been a pleasure

**Comment by gierschv** [comment]
@revollat The permissions of the mounted volumes are preserved when mounted inside the container, therefore you need to provided a directory where the user `ghost` can read / write:

``` bash
$ docker run --rm -p 80:2368 -v /root:/ghost-override -it ghost  /bin/bash
ghost@0c236c57a4cd:/ghost$ id ghost
uid=1000(ghost) gid=1000(ghost) groups=1000(ghost)
ghost@0c236c57a4cd:/ghost$ ls -l / | grep ghost-override
drwx------   5 root  root  4096 Oct 11 11:14 ghost-override

$ mkdir ~/ghost-override && chown 1000:1000 ~/ghost-override
$ docker run --rm -p 80:2368 -v ~/ghost-override:/ghost-override -it ghost /bin/bash
ghost@78c2c92565d0:/ghost$ ls -l / | grep ghost-override
drwxrwxr-x   2 ghost ghost 4096 Oct 16 20:08 ghost-override
```

I proposed an update: #17.

**Pull request merged**
